# Generated by Django 5.0.6 on 2024-07-05 11:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additionalComments', models.TextField()),
                ('fullName', models.CharField(max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('organizationName', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BasicInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameOfTheIndustry', models.CharField(max_length=200)),
                ('Telephone', models.PositiveBigIntegerField(validators=[django.core.validators.MaxValueValidator(999999999999)])),
                ('WebsiteLink', models.URLField(blank=True, default='No Website Link', null=True)),
                ('ContactEmail', models.EmailField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Of_Registration', models.DateField(blank=True, null=True)),
                ('Registration_Number', models.CharField(blank=True, max_length=200, null=True)),
                ('Name_Of_The_Contact_Person', models.CharField(blank=True, max_length=200, null=True)),
                ('TelNo_Of_The_Contact_Person', models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999999)])),
                ('Title_Of_The_Contact_Person', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.CharField(default='No Reason', max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EducationCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_Formal_Education', models.PositiveIntegerField()),
                ('PLE', models.PositiveIntegerField()),
                ('UCE', models.PositiveIntegerField()),
                ('UACE', models.PositiveIntegerField()),
                ('Certificate', models.PositiveIntegerField()),
                ('Diploma', models.PositiveIntegerField()),
                ('Degree', models.PositiveIntegerField()),
                ('Post_Graduate', models.PositiveIntegerField()),
                ('Total', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permanent_male', models.PositiveIntegerField(default=0)),
                ('permanent_female', models.PositiveIntegerField(default=0)),
                ('contract_male', models.PositiveIntegerField(default=0)),
                ('contract_female', models.PositiveIntegerField(default=0)),
                ('casual_male', models.PositiveIntegerField(default=0)),
                ('casual_female', models.PositiveIntegerField(default=0)),
                ('self_employed_male', models.PositiveIntegerField(default=0)),
                ('self_employed_female', models.PositiveIntegerField(default=0)),
                ('other_male', models.PositiveIntegerField(default=0)),
                ('other_female', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HostingExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_hosted_apprentices', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('experience_details', models.TextField(blank=True, null=True)),
                ('max_apprentices', models.IntegerField()),
                ('support_description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District', models.CharField(max_length=100)),
                ('Constituency', models.CharField(max_length=100)),
                ('Sub_county', models.CharField(max_length=200)),
                ('Parish', models.CharField(max_length=200)),
                ('Village', models.CharField(max_length=100)),
                ('GPS_Points', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999999)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targeted_trade', models.CharField(max_length=255)),
                ('reason_for_partnership', models.TextField()),
                ('enterprise_size', models.CharField(max_length=255)),
                ('dev_stage', models.CharField(max_length=255)),
                ('track_record', models.TextField()),
                ('expertise', models.TextField()),
                ('staff_mentoring', models.TextField()),
                ('infrastructure', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile', models.PositiveBigIntegerField(validators=[django.core.validators.MaxValueValidator(999999999999)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkPlacementCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=100)),
                ('hosting_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='form_register.hostingexperience')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
