# Generated by Django 5.0.6 on 2024-07-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_register', '0002_alter_physicaladdress_gps_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='sector_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
