# Generated by Django 5.0.6 on 2024-08-02 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_register', '0002_files_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacity',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='form_register.files'),
        ),
    ]
