# Generated by Django 5.0.6 on 2024-07-29 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_register', '0003_trade_sector_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workplacementcourse',
            name='hosting_experience',
        ),
        migrations.AddField(
            model_name='workplacementcourse',
            name='trade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='form_register.trade'),
            preserve_default=False,
        ),
    ]
