# Generated by Django 5.0.6 on 2024-08-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_register', '0003_alter_capacity_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environmentalWasteManagement', models.CharField(max_length=400)),
                ('environmentalConservation', models.CharField(max_length=400)),
                ('socialCommunityEngagement', models.CharField(max_length=400)),
                ('socialLocalSuppliers', models.CharField(max_length=400)),
                ('socialCSRInitiatives', models.CharField(max_length=400)),
                ('safetyHealthPolicy', models.CharField(max_length=400)),
                ('safetyCommunication', models.CharField(max_length=400)),
                ('safetyEmergencyProcedures', models.CharField(max_length=400)),
                ('safetySafeEnvironment', models.CharField(max_length=400)),
                ('healthHygieneSanitation', models.CharField(max_length=400)),
                ('healthWellnessPrograms', models.CharField(max_length=400)),
            ],
        ),
    ]
