# Generated by Django 5.0.6 on 2024-07-29 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_register', '0004_remove_workplacementcourse_hosting_experience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workplacementcourse',
            old_name='sn',
            new_name='module_code',
        ),
        migrations.RenameField(
            model_name='workplacementcourse',
            old_name='course_name',
            new_name='module_name',
        ),
    ]
