# Generated by Django 5.0.6 on 2024-07-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_register', '0005_rename_sn_workplacementcourse_module_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacity',
            name='certificate',
            field=models.FileField(default=1, upload_to='files/'),
            preserve_default=False,
        ),
    ]
