# Generated by Django 5.0.6 on 2024-08-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_register', '0005_environment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='safetyCommunication',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
