# Generated by Django 5.0.6 on 2024-07-29 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_register', '0006_capacity_certificate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeecategory',
            old_name='other_female',
            new_name='consultants_female',
        ),
        migrations.RenameField(
            model_name='employeecategory',
            old_name='other_male',
            new_name='consultants_male',
        ),
        migrations.RemoveField(
            model_name='employeecategory',
            name='self_employed_female',
        ),
        migrations.RemoveField(
            model_name='employeecategory',
            name='self_employed_male',
        ),
    ]
