# Generated by Django 5.0.6 on 2024-08-06 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_register', '0006_alter_environment_safetycommunication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environment',
            old_name='environmentalConservation',
            new_name='Available_channels',
        ),
        migrations.RenameField(
            model_name='environment',
            old_name='environmentalWasteManagement',
            new_name='Harrasment_Prevention',
        ),
        migrations.RenameField(
            model_name='environment',
            old_name='healthHygieneSanitation',
            new_name='provided_PPES',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='healthWellnessPrograms',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='safetyCommunication',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='safetyEmergencyProcedures',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='safetyHealthPolicy',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='safetySafeEnvironment',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='socialCSRInitiatives',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='socialCommunityEngagement',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='socialLocalSuppliers',
        ),
    ]
