# Generated by Django 5.0.6 on 2024-08-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_register', '0008_agriculture_agroprocessing_beauty_and_cosmetology_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='skills',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
