# Generated by Django 5.0.6 on 2024-08-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_register', '0009_alter_trade_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='This message is to confirm that your application for the Grow Host Instutions vacancy has been received successfully. A confirmation e-mail has been sent to you Regards, GROW Team', max_length=255)),
            ],
        ),
    ]
